[package]
name = "yuragi-wasm-compiler"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.103"
itertools = "0.14.0"
lyon_algorithms = "1.0.5"
lyon_path = "1.0.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
skrifa = { version = "0.44.0", default-features = false, features = ["std"] }
unicode-linebreak = "0.1.5"
unicode-segmentation = "1.12.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
